services:
  # API Service
  - type: web
    name: trainer-tracker-api
    env: node
    plan: starter
    buildCommand: cd apps/api && npm install && npx prisma generate && npx prisma migrate deploy && npm run seed && npm run build
    startCommand: cd apps/api && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trainer-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3001
      - key: HOSTNAME
        value: 0.0.0.0
    healthCheckPath: /api/health

  # Web Service
  - type: web
    name: trainer-tracker-web
    env: node
    plan: starter
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://trainer-tracker-api.onrender.com
      - key: PORT
        value: 3000
      - key: HOSTNAME
        value: 0.0.0.0
    healthCheckPath: /

databases:
  - name: trainer-tracker-db
    databaseName: trainer_tracker
    user: trainer_tracker_user
    plan: starter 